# editor settings
theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

# keymap
[keys.insert]
j = { k = "normal_mode" }

