# editor settings
theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "separator", "version-control", "separator", "file-name"]
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-type"]
separator = " │ "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# keymap
[keys.insert]
j = { k = "normal_mode" }

