[[session]]
name = "notetaking"
path = "~/Documents/Grafana Labs"
startup_command = "tmux new-window -d && nvim_cshih"

[[session]]
name = "grafana analytics"
path = "~/projects/grafana_analytics"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "grafana-analytics-agent"
path = "~/projects/grafana-analytics-agent"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "product analytics"
path = "~/projects/product_analytics"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "dbt"
path = "~/projects/dbt_grafanalabs_global"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "prefect"
path = "~/projects/prefect"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "prefect2"
path = "~/projects/prefect2"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "deployment_tools"
path = "~/projects/deployment_tools"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "projects"
path = "~/projects"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "dotfiles"
path = "~/projects/dotfiles"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "default"
path = "~"
