# Product Analytics Repo
[[session]]
name = "product analytics"
path = "~/projects/product_analytics"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "dbt"
path = "~/projects/dbt_grafanalabs_global"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "prefect"
path = "~/projects/prefect2"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "deployment_tools"
path = "~/projects/deployment_tools"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "projects"
path = "~/projects"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "Obsidian"
path = "~/Documents/Grafana Labs"
startup_command = "nvim_cshih"

[[session]]
name = "dotfiles"
path = "~/projects/dotfiles"
startup_command = "tmux new-window -d && tmux new-window -d && nvim_cshih"

[[session]]
name = "default"
path = "~"
