#!/bin/sh

export ZSH="/home/chris/.oh-my-zsh"

ZSH_THEME="eastwood"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"

# Color completion the same as ls
eval "$(dircolors)"
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# Other options
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

if [[ -a ~/.local.zshrc ]]; then
	source ~/.local.zshrc
fi

# # source
# plug "$HOME/.config/zsh/aliases.zsh"
# plug "$HOME/.config/zsh/exports.zsh"

# # plugins
# plug "esc/conda-zsh-completion"
# plug "zsh-users/zsh-autosuggestions"
# plug "hlissner/zsh-autopair"
# plug "zap-zsh/supercharge"
# plug "zap-zsh/vim"
# plug "zap-zsh/zap-prompt"
# plug "zap-zsh/fzf"
# plug "zap-zsh/exa"
# plug "zsh-users/zsh-syntax-highlighting"

# # keybinds
# bindkey '^ ' autosuggest-accept

#------------------------
#-- User configuration --
#------------------------

# PATH updates
export PATH=$PATH:/usr/local/git/bin:/usr/local/bin
export LANG=en_US.UTF-8
export PATH="$PATH:/home/chris/julia-1.7.2/bin"
export PATH=/home/chris/.local/bin:$PATH

#-------------
#-- Aliases --
#-------------

# basic aliases
export EDITOR='lvim'
alias ls='ls -FG --color=auto'
alias vi='lvim'
alias vim='lvim'

# git aliases
alias gs='git status'
alias gl='git pull'
alias gp='git push'
alias gd='git diff'
alias oops='git reset --soft HEAD^'

# data aliases
alias python='python3'
alias cclip='xclip -selection clipboard'

alias run_docker_gpu='docker run -it --gpus all --rm -p 8888:8888 -v /home/chris/project:/home -w /home -u $(id -u):$(id -g) tensorflow bash'
alias source_env_dbt='source /home/chris/project/dbt/dbt-env/bin/activate'
alias run_zoom='zoom --disable-gpu-sandbox'


#--------------
#-- Anaconda --
#--------------

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/chris/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/chris/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/chris/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/chris/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

#------------
#-- Gcloud --
#------------

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/chris/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/chris/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/chris/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/chris/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
