model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

web_search = "live"

personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"

[features]
skills = true

multi_agent = true
collaboration_modes = true
steer = true
prevent_idle_sleep = true
default_mode_request_user_input = true

[projects."/Users/chris/projects/dotfiles"]
trust_level = "trusted"

[projects."/Users/chris/projects/product_analytics"]
trust_level = "trusted"

[projects."/Users/chris/projects/grafana_analytics"]
trust_level = "trusted"

[projects."/Users/chris/projects/dae_example_data_agent"]
trust_level = "trusted"

[projects."/Users/chris/projects/dbt_grafanalabs_global"]
trust_level = "trusted"

[projects."/Users/chris/projects/GrafanaCON2026-business-data-stack"]
trust_level = "trusted"
